groups:
- name: native
  jobs: [A, B]

jobs:
- name: A
  plan: &cacheplan
  - task: t01
    config: &cachetask
      platform: linux
      image_resource:
        type: docker-image
        source:
          insecure_registries: ((docker.insecure_registries))
          repository: ((docker.registry))alpine
          tag: 3.8
      caches:
      - path: cache
      run:
        path: ash
        args:
        - -c
        - |
          echo "============================================================================"
          echo '   ---   Cache content   ---'
          ls -lR cache
          echo

          filename=$(date '-Iseconds' | tr ':+' '--')
          echo "   ---   Put ${filename}   ---"
          date > "cache/${filename}"
          ls -lR cache
          echo
  - task: t02
    config: *cachetask

- name: B
  plan: *cacheplan
