platform: linux
image_resource:
  type: docker-image
  source:
    insecure_registries: ((docker.insecure_registries))
    repository: ((docker.registry))maven
    tag: 3.5.4
inputs:
- name: src
- name: repository.in
  optional: true
outputs:
- name: repository.out
run:
  path: src/src/ci/scripts/compile.sh
