jobs:
- name: hello
  plan:
  - task: say Hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          insecure_registries: ((docker.insecure_registries))
          repository: ((docker.registry))alpine
          tag: 3.8
      run: { path: echo,  args: ['Hello'] }
