jobs:
- name: Hello
  plan:
  - task: say Hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: alpine, tag: 3.8 }
      run: { path: echo,  args: ['Hello'] }
