platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: 3.8

inputs:
- name: source
- name: cache
  optional: true

outputs:
- name: result

run:
  path: source/scripts/build.sh
