platform: linux
image_resource:
    type: docker-image
    source:
        insecure_registries: ((docker.insecure_registries))
        repository: ((docker.registry))alpine
        tag: 3.8
run: { path: src/ci/scripts/hello.sh }
inputs:
- name: src
- name: recipient
