platform: linux
image_resource:
  type: docker-image
  source:
    insecure_registries: ((docker.insecure_registries))
    repository: ((docker.registry))loganmzz/rust
    tag: 1.28.0
run:
  user: root
  path: ci/scripts/rust-test.sh
inputs:
- name: ci
- name: src
