groups:

- name: release
  jobs: [prepare-release, generate-release]

- name: version
  jobs: [bump-major, bump-minor]



resources:

- name: version
  type: semver
  source:
    driver: s3
    endpoint: ((s3.endpoint))
    bucket: ((s3.bucket))
    access_key_id: ((s3.access_key_id))
    secret_access_key: ((s3.secret_access_key))
    key: version/version.txt

- name: git
  type: git
  source:
    uri: ((git.base-uri))version.git
    private_key: ((git.private-key))

- name: source
  type: s3
  source:
    endpoint: ((s3.endpoint))
    disable_ssl: ((s3.disable_ssl))
    bucket: ((s3.bucket))
    access_key_id: ((s3.access_key_id))
    secret_access_key: ((s3.secret_access_key))
    regexp: version/sources/demo-(.*)-src.tar.gz

- name: release
  type: s3
  source:
    endpoint: ((s3.endpoint))
    disable_ssl: ((s3.disable_ssl))
    bucket: ((s3.bucket))
    access_key_id: ((s3.access_key_id))
    secret_access_key: ((s3.secret_access_key))
    regexp: version/releases/demo-(.*)


- name: cargo-bump
  type: s3
  source:
    endpoint: ((s3.endpoint))
    disable_ssl: ((s3.disable_ssl))
    bucket: ((s3.bucket))
    access_key_id: ((s3.access_key_id))
    secret_access_key: ((s3.secret_access_key))
    regexp: cargo-bump-(.*)



jobs:

- name: prepare-release
  plan:
  - get: git
  - put: version
    params: { bump: patch }
  - get: cargo-bump
  - task: new
    file: git/ci/tasks/prepare-release.yml
  - put: source
    params: { file: source/demo-*-src.tar.gz }

- name: generate-release
  plan:
  - get: source
    params: { unpack: true }
    passed: [prepare-release]
    trigger: true
  - task: build
    file: source/ci/tasks/generate-release.yml
  - put: release
    params: { file: release/demo-* }


- name: bump-major
  plan:
  - put: version
    params: { bump: major }

- name: bump-minor
  plan:
  - put: version
    params: { bump: minor }
