jobs:
- name: long-job
  plan:
  - task: long-task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          insecure_registries: ((docker.insecure_registries))
          repository: ((docker.registry))alpine
          tag: 3.8
      run:
        path: ash
        args:
        - c
        - |
          sleep 300
